demohub:
  outputs:
    dev:
      account: liifdms-cx19744
      database: dbt_demo
      password: Lateralus0!
      role: accountadmin
      schema: employee_data
      threads: 4
      client_session_keep_alive: false
      query_tag: dbt
      type: snowflake
      user: rtewelde
      warehouse: compute_wh
  target: dev
