demohub:
  outputs:
    dev:
      account: cixgwzi-mu81305
      database: demo_dbt
      password: Lateralus85!
      role: accountadmin
      schema: employee_data
      threads: 1
      type: snowflake
      user: rtewelde
      warehouse: compute_wh
  target: dev
