name: Run dbt Models

on:
  push:
    branches:
      - '*'  # Trigger for any branch

env:
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_PASSWORD: ${{ secrets.SF_PW }}
  SF_ROLE: ${{ secrets.SF_ROLE }}
  SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
  SF_DATABASE: ${{ secrets.SF_DB }}
  SF_SCHEMA: ${{ secrets.SF_SCHEMA }}

jobs:
  run-dbt-models:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: dbt_demo  # Use a relative path within the GitHub Actions workspace

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dbt and Snowflake adapter
      run: |
        pip install dbt-core
        pip install dbt-snowflake
        dbt --version

    - name: Set up dbt
      run: |
        mkdir -p $HOME/.dbt
        chmod -R 777 $HOME/.dbt  # Ensure read, write, and execute permissions
        cp demohub/profiles.yml $HOME/.dbt/
        cp demohub/dbt_project.yml $HOME/.dbt/

    - name: Print contents of $HOME/.dbt/
      run: ls -R $HOME/.dbt/
      
    - name: Print current working directory
      run: pwd

    - name: Print contents of models directory
      run: ls -R models/

    - name: dbt debug
      run: dbt debug --profiles-dir $HOME/.dbt/ --project-dir $HOME/.dbt/

    - name: Run dbt tests and models
      run: |
        dbt test --profiles-dir $HOME/.dbt/ --project-dir $HOME/.dbt/
        DBT_DEBUG=true dbt run --profiles-dir $HOME/.dbt/ --project-dir $HOME/.dbt/ --models +model_name
