name: Run dbt Models

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  run-dbt-models:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dbt
      run: |
        pip install dbt-core
        dbt --version

    - name: Copy profiles.yml
      run: cp /Users/rtewelde/dbt_demo/demohub/profiles.yml $HOME/.dbt/

    - name: Copy dbt_project.yml
      run: cp /Users/rtewelde/dbt_demo/demohub/dbt_project.yml $HOME/.dbt/

    - name: dbt debug
      run: dbt debug --profiles-dir ~/.dbt/

    - name: Run dbt models
      run: |
        cd /Users/rtewelde/dbt_demo/demohub  # Change to the directory containing your dbt_project.yml
        dbt run
