name: Run dbt Models

on:
  push:
    branches:
      - main  # Adjust to your main branch name

env:
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_PASSWORD: ${{ secrets.SF_PW }}
  SF_ROLE: ${{ secrets.SF_ROLE }}
  SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
  SF_DATABASE: ${{ secrets.SF_DB }}
  SF_SCHEMA: ${{ secrets.SF_SCHEMA }}

jobs:
  run-dbt-models:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dbt and Snowflake adapter
      run: |
        pip install dbt-core
        pip install dbt-snowflake
        dbt --version

    - name: Ensure required directories exist
      run: |
        mkdir -p $HOME/.dbt
        chmod -R 777 $HOME/.dbt  # Ensure read, write, and execute permissions

    - name: Print current working directory
      run: pwd

    - name: List files in the root directory
      run: ls -R

    - name: Copy profiles.yml to $HOME/.dbt/
      run: |
        if [ -e "demohub/profiles.yml" ]; then
          cp demohub/profiles.yml $HOME/.dbt/
        else
          echo "Error: profiles.yml not found in the demohub directory."
          ls -R demohub
          ls -R $HOME/.dbt/
          exit 1
        fi

    - name: Print contents of $HOME/.dbt/
      run: ls -R $HOME/.dbt/

    - name: dbt debug
      run: dbt debug --profiles-dir $HOME/.dbt/

    - name: Run dbt tests and models
      run: |
        dbt test && dbt run
