name: Run dbt Models

on:
  push:
    branches:
      - main  # Adjust to your main branch name

env:
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_PASSWORD: ${{ secrets.SF_PW }}
  SF_ROLE: ${{ secrets.SF_ROLE }}
  SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
  SF_DATABASE: ${{ secrets.SF_DB }}
  SF_SCHEMA: ${{ secrets.SF_SCHEMA }}

jobs:
  run-dbt-models:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dbt
      run: |
        pip install dbt-core
        dbt --version

    - name: Ensure .dbt directory exists
      run: mkdir -p $HOME/.dbt

    - name: Copy profiles.yml
      run: cp dbt_demo/demohub/profiles.yml $HOME/.dbt/

    - name: Configure Environment Variables
      run: |
        echo "Configuring environment variables..."
        export PATH=$PATH:/opt/hostedtoolcache/Python/3.11.5/x64/bin
        export LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.11.5/x64/lib
        export SF_ACCOUNT=$SF_ACCOUNT
        export SF_USERNAME=$SF_USERNAME
        export SF_PASSWORD=$SF_PASSWORD
        export SF_ROLE=$SF_ROLE
        export SF_WAREHOUSE=$SF_WAREHOUSE
        export SF_DATABASE=$SF_DATABASE
        export SF_SCHEMA=$SF_SCHEMA

    - name: dbt debug
      run: dbt debug --profiles-dir ~/.dbt/ 

    - name: Run dbt models
      run: |
        cd dbt_demo/demohub  # Change to the directory containing your dbt_project.yml
        dbt run
