name: Run dbt Models

on:
  push:
    branches:
      - main  # Adjust to your main branch name

env:
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_PASSWORD: ${{ secrets.SF_PW }}
  SF_ROLE: ${{ secrets.SF_ROLE }}
  SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
  SF_DATABASE: ${{ secrets.SF_DB }}
  SF_SCHEMA: ${{ secrets.SF_SCHEMA }}

jobs:
  run-dbt-models:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dbt
      run: |
        pip install dbt-core
        dbt --version

    - name: Ensure required directories exist
      run: |
        mkdir -p $HOME/.dbt
        mkdir -p dbt_demo/demohub
        chmod -R 777 $HOME/.dbt  # Ensure read, write, and execute permissions

    - name: Print current working directory
      run: |
        pwd
        ls -R dbt_demo/demohub

    - name: Change to dbt_demo/demohub directory
      run: cd dbt_demo/demohub

    - name: Debug - Check files in dbt_demo/demohub
      run: |
        ls -a
        cat profiles.yml

    - name: Check if profiles.yml exists
      run: |
        if [ -e "profiles.yml" ]; then
          echo "profiles.yml exists in dbt_demo/demohub/ directory."
          cp profiles.yml $HOME/.dbt/
        else
          echo "Error: profiles.yml not found in dbt_demo/demohub/ directory."
          ls -a  # Print directory contents for debugging
          ls -a $HOME/.dbt/  # Print contents of $HOME/.dbt/ for debugging
          exit 1  # Exit the workflow with an error code if the file doesn't exist
        fi

    - name: Print contents of $HOME/.dbt/
      run: |
        ls -R $HOME/.dbt/

    - name: Print contents of dbt_demo/demohub
      run: |
        ls -R dbt_demo/demohub

    - name: dbt debug
      run: dbt debug --profiles-dir $HOME/.dbt/

    - name: Run dbt tests and models
      run: |
        dbt test && dbt run
