name: Run dbt Models

on:
  push:
    branches:
      - main  # Adjust to your main branch name

env:
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_PASSWORD: ${{ secrets.SF_PW }}
  SF_ROLE: ${{ secrets.SF_ROLE }}
  SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
  SF_DATABASE: ${{ secrets.SF_DB }}
  SF_SCHEMA: ${{ secrets.SF_SCHEMA }}

jobs:
  run-dbt-models:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dbt
      run: |
        pip install dbt-core
        dbt --version

    - name: Ensure required directories exist
      run: |
        mkdir -p $HOME/.dbt
        mkdir -p dbt_demo/demohub
        chmod -R 777 $HOME/.dbt  # Ensure read, write, and execute permissions

    - name: Copy profiles.yml, dbt_project.yml, and .dbt.yml
      run: |
        cp dbt_demo/demohub/profiles.yml $HOME/.dbt/
        cp dbt_demo/demohub/dbt_project.yml dbt_demo/demohub/.dbt.yml $HOME/.dbt/

    - name: Print current working directory
      run: |
        pwd
        ls -R dbt_demo/demohub

    - name: Check if profiles.yml exists
      run: |
        if [ -e "dbt_demo/demohub/profiles.yml" ]; then
          echo "profiles.yml exists in dbt_demo/demohub/ directory."
        else
          echo "profiles.yml does not exist in dbt_demo/demohub/ directory."
          ls -R dbt_demo/demohub  # Print directory contents for debugging
          # You can add error handling or take appropriate action here if needed.
          exit 1  # Exit the workflow with an error code if the file doesn't exist
        fi

    - name: dbt debug
      run: dbt debug --profiles-dir $HOME/.dbt/

    - name: Run dbt tests and models
      run: |
        cd dbt_demo/demohub  # Change to the directory containing your dbt_project.yml
        dbt test && dbt run
